# This script takes the RP2040 runtimes generated by build-rts.py and
# patches them to turn them into an Alire crate.
#
# In particular it:
#  - adds an alire.toml
#  - patches target_options.gpr to add a prefix to the BUILD and LIBRARY_TYPE
#    GPR scenario variables.
#  - adds rp2040_runtime_config.ads which renames the crate config package
#    generated by Alire so that the common runtime sources can access the
#    config via one common package name.

import argparse
import pathlib
import shutil
from typing import Dict


def patch_target_options(gpr_file: pathlib.Path, profile: str, target: str):
    """Patch the target_options.gpr file to add the crate name as a prefix
    to GPR variables.

    E.g. for light-tasking-rp2040:
    BUILD becomes LIGHT_TASKING_RP2040_BUILD
    LIBRARY_TYPE becomes LIGHT_TASKING_RP2040_LIBRARY_TYPE

    This follows the Alire best practices and allows the build mode to be
    set for just the runtime crate if need be.
    """

    # Change "light-tasking" to "light_tasking"
    profile = profile.replace("-", "_")

    with open(gpr_file, "r") as f:
        content = f.read()

    content = content.replace(
        f'"BUILD"',
        f'"{profile.upper()}_{target.upper()}_BUILD"',
    )
    content = content.replace(
        f'"LIBRARY_TYPE"',
        f'"{profile.upper()}_{target.upper()}_LIBRARY_TYPE"',
    )

    with open(gpr_file, "w") as f:
        f.write(content)


def gen_from_template(
    template_file: pathlib.Path,
    out_file: pathlib.Path,
    template_values: Dict[str, str],
):
    with open(template_file, "r") as f:
        content = f.read()

    for key, value in template_values.items():
        content = content.replace(f"$({key})", value)

    with open(out_file, "w", newline="\n") as f:
        f.write(content)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--runtime-dir", type=str, help="Path to the runtime directory to patch"
    )
    parser.add_argument(
        "--profile",
        type=str,
        choices=["light", "light-tasking", "embedded"],
        help="The runtime profile",
    )
    parser.add_argument(
        "--pretty-target",
        type=str,
        help="The pretty name of the target (e.g. RP2040). Must not contain spaces",
    )
    parser.add_argument(
        "--version",
        type=str,
        default="15.0.0-dev",
        help="Version string to put in the alire.toml file",
    )

    args = parser.parse_args()

    runtime_dir = pathlib.Path(args.runtime_dir)
    profile = args.profile
    pretty_target = args.pretty_target
    target = pretty_target.lower().replace("-", "_")

    has_libgnarl = (runtime_dir / "ravenscar_build.gpr").exists()

    project_files = ["runtime_build.gpr"]
    if has_libgnarl:
        project_files.append("ravenscar_build.gpr")

    patch_target_options(
        gpr_file=runtime_dir / "target_options.gpr", profile=profile, target=target
    )

    # light and light-tasking require "Ada" and "Asm_Cpp".
    # embedded also requires "C".
    languages_list = ["Ada", "Asm_Cpp"]
    if profile == "embedded":
        languages_list.append("C")

    template_values = {
        "profile": profile,
        "profile_underscored": profile.replace("-", "_"),
        "target": target,
        "pretty_target": pretty_target,
        "project_files_list": str(project_files),
        "version": args.version,
        "languages_list": ", ".join(f'"{lang}"' for lang in languages_list),
    }

    templates_dir = pathlib.Path(__file__).parent / "templates"

    gen_from_template(
        template_file=templates_dir / "alire.toml.in",
        out_file=runtime_dir / "alire.toml",
        template_values=template_values,
    )

    gen_from_template(
        template_file=templates_dir / "rp2040_runtime_config.ads.in",
        out_file=runtime_dir / "gnat_user" / "rp2040_runtime_config.ads",
        template_values=template_values,
    )

    gen_from_template(
        template_file=templates_dir / "runtime_build.gpr.in",
        out_file=runtime_dir / "runtime_build.gpr",
        template_values=template_values,
    )

    if has_libgnarl:
        gen_from_template(
            template_file=templates_dir / "ravenscar_build.gpr.in",
            out_file=runtime_dir / "ravenscar_build.gpr",
            template_values=template_values,
        )

    shutil.copytree(
        src=pathlib.Path(__file__).parent / "rp_src" / "ld",
        dst=runtime_dir / "ld",
        dirs_exist_ok=True,
    )

if __name__ == "__main__":
    main()
